version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    networks:
      - backend
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

  db:
    build:
      context: .
      dockerfile: Dockerfile.DB
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PORT
    networks:
      - backend

networks:
  backend:
